feat: 사전 모집 이벤트 초대코드 추가
BookBLA/americano pull request #436
Opened 2024-10-19 16:20 UTC by leevigong

## 📄 Summary

> 이번 사전 모집에 사용할 얼리버드 초대코드를 이벤트 코드로 추가하므로써 기존 축제 코드와 분리하여 작성.
> 앞으로 다양한 축제와 이벤트가 열릴 것으로 보아 축제와 이벤트 관련 초대코드 및 책갈피 보상을 상수클래스(InvitationConstants)에 모아 작성.

## 🙋🏻 More

>

2024-10-19 18:57 UTC, iamjooon2 requested changes
안녕하세요 다은님

리뷰어로 달아주셔서 살펴봤는데요
제 코드랑 똑같아서.. 어떤 주안점을 가지고 봐야할지 모르겠습니다

시간에 쫓겨 급하게 넣은 변수/함수는 그대로 쓰셨는데
제가 잘못 적어둔 테스트 명세는 바꿔주셨고..

시간이 촉박하다면, 기능을 쳐내기 위해
기존에 동작하던 코드를 가져다 쓸 순 있을 것 같은데
앱 출시 완료된 지금이 그런 상황은 아닌 것 같고..

이 PR을 제게 리뷰 요청 주신게 어떤 의미인지 잘 모르겠습니다...
상수화하신 부분 하나 남겼습니다

2024-10-19 18:57 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/school/service/dto/InvitationConstants.java
> +public class InvitationConstants {
다은님이 생각하시는 dto는 어떤 역할을 하는지 말씀해주실 수 있나요?!

2024-10-19 19:09 UTC, merged

2024-10-20 07:04 UTC, Hangyeol-SSeo commented on src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationType.java
> +    EVENT
앞으로 이벤트가 계속 늘어날텐데 이 변수명은 좀 아닌거같습니다...
프론트에서도 이렇게 하면 유지보수할때 어려움이 생길 것 같고요.
EARLY_BIRD같은 특정성 있는걸로 나중에 바꿔야 할 것 같네요

추가로 이벤트 코드의 활성 비활성이 있는지 모르겠지만 없다면 그것도 만들어야 합니다.
언제까지고 모든 이벤트코드를 풀어둘순 없으니깐요.

2024-10-20 10:07 UTC, leevigong commented
처음 본 코드이고 원래 있던 부분에서 약간 분리시켜서 작성해서 빠진 부분 없이 흐름상 맞게 작성했는지 확인받기 위해서 리뷰어 요청드렸습니다..!
사실 다음주 시험이라 스스로 약간 시간에 쫒겨서 작성한 부분이 없지않아있습니다 죄송합니다ㅜ  

dto는 데이터 전송을 위한 객체이니 상수를 여기다 넣으면 패키지 목적이 혼란스러워지니 이부분은 수정하겠습니다 

한결님 말씀대로 이벤트코드나 축제코드를 무한정 열어둘 수 없으니 이부분도 고려해야할거같네요!

2024-10-20 10:08 UTC, leevigong commented on src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationType.java
> +    EVENT
이벤트로 크게 잡아둔건데 생각해보니 세부 이벤트를 저장하는 부분이 없어서 특정성 있게 가야할거같네요