Fix: 계정 설정 및 푸시 알림 변경
BookBLA/americano pull request #87
Opened 2024-05-31 09:22 UTC by GinToFim

## 📄 Summary

1. `MemberPushAlarmResponse` -> `MemberPushAlarmReadResponse` 이름 변경
2. yaml 파일에 정의되어 있는 계정을 도현님 계정으로 수정
3. 모든 멤버에게 보내는 푸시 알림 API 구현

>

## 🙋🏻 More

>

2024-05-31 09:50 UTC, iamjooon2 requested changes
빠르게 남겨보았습니다

몇가지만 확인부탁드릴게요!

2024-05-31 09:50 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +            .collect(Collectors.toList());
데이터베이스에 이미 엑스포 토큰 형식으로 저장되어있는 것 같습니다! 확인 한 번 부탁드릴게요!

2024-05-31 09:50 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/controller/AlarmController.java
> +    }
사용자가 사용자에게 전체 알림을 보낼 일은 없을 것 같습니다

테스트용으로 만들어둔거면, 어차피 사용해야하는 어드민에 만들어두는 것은 어떨까요?

2024-05-31 09:50 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/controller/dto/response/PushAlarmAllCreateResponse.java
> +public class PushAlarmAllCreateResponse {
사용자로부터 받은 푸쉬알림의 제목과 내용을 다시 돌려주진 않아도 될 것 같아요

성공했다는 의미로 전달하려 하셨던 거라면, 기본 응답에 있는 isSuccess로도 확인할 수 있을 것 같습니다
만들었으니 바꾸진 마시죠!

2024-05-31 09:50 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +        List<Member> members = memberRepository.findAll();
잘 몰라서 여쭤봅니다
기획적으로 모든 회원에게 일괄적으로 푸시 알림을 전송해도 괜찮은가요?

2024-05-31 09:56 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +        }
배치별로 나누어 보내는건가요?

2024-05-31 09:57 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +        }
사이즈별로 잘라 나누어 보내는 걸로 이해했습니다. 맞나요?!

2024-05-31 15:48 UTC, GinToFim commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +        List<Member> members = memberRepository.findAll();
기획적으로 공지사항이나 이벤트 알림이 있을 경우 모든 유저에게 푸시 알림을 전송될 거 같습니다!

2024-05-31 15:48 UTC, GinToFim commented on src/main/java/com/bookbla/americano/domain/alarm/controller/AlarmController.java
> +    }
네넵 해당 api를 admin하고 연결하면 될 것 같습니다!

2024-05-31 15:52 UTC, GinToFim commented on src/main/java/com/bookbla/americano/domain/alarm/controller/dto/response/PushAlarmAllCreateResponse.java
> +public class PushAlarmAllCreateResponse {
아하 그렇네요! 해당 ResponseDto는 나중에 수정하겠습니다

2024-05-31 16:19 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +        }
좋습니다👍

코드에 문서 링크 달아두면 더 좋을 것 같아요👍👍

2024-05-31 16:27 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/alarm/controller/AlarmController.java
> +    }
머지되고 제가 반영해두겠습니다~

2024-06-02 04:40 UTC, GinToFim commented on src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java
> +            .collect(Collectors.toList());
프론트 쪽에서 해당 형식으로 보내시는 것으로 확인되어서 말씀드렸습니다!

2024-06-02 05:15 UTC, iamjooon2 approved these changes
고생하십니다🫡

2024-06-02 05:15 UTC, iamjooon2 commented on src/main/java/com/bookbla/americano/domain/admin/service/AdminMemberService.java
> -            memberVerify.success(dto.getReason());
요거 다시 넣어주실 수 있을까용?!

2024-06-02 05:16 UTC, merged